version: '3.4'

services:
    front:
        build: .
        container_name: front
        restart: unless-stopped
        environment:
            - VITE_API_URI=${VITE_API_URI}
        ports:
            - 80:80
