version: "3.4"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD=12345
      - POSTGRES_USER=rksp
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=booking
    volumes:
      - pg-data:/var/lib/postgresql/data

  rksp:
    build: .
    container_name: rksp_server
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    links:
      - db
    volumes:
    - ./:/app
    ports:
     - "8080:8080"

volumes:
  pg-data:
