version: '3.4'

services:
    db:
        image: postgres:16-alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_ROOT_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - dbnet

    server:
        build: .
        container_name: server
        depends_on:
            - db
        networks:
            - dbnet
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public&sslmode=disable
            - PORT=${PORT}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - ${PORT}:${PORT}

volumes:
    pg-data:

networks:
  dbnet:
